### ISSUE TITLE
exception on selecting char

### ISSUE THREAD

**Issue by MarvinFS** [GLotsapot/HellionSaveEditor#1]
when you select a character in drops with exception. server is stopped during try, server version (official) 0.1.10 client version 0.1.10

![2017-04-27_03-08-22](https://cloud.githubusercontent.com/assets/7998636/25459389/6765d570-2af7-11e7-9415-62fd1c5dd0d1.png)

**Comment by GLotsapot** [comment]
I can see that it says it cannot find a save file when you start the program, which tells me you most likely have the HellionSaveEditor.exe in the wrong folder. Create a folder in your "Hellion Dedicated Server" and put it in there. 
I will update my code so that if it can't find a save game to edit, that it won't allow you to try other commands.

**Comment by GLotsapot** [comment]
Code pushed to repository and will be available in the next binary release.
